name       : xcb-util-wm
version    : 0.4.1
release    : 4
source     :
    - http://xcb.freedesktop.org/dist/xcb-util-wm-0.4.1.tar.bz2 : 28bf8179640eaa89276d2b0f1ce4285103d136be6c98262b6151aaee1d3c2a3f
license    : MIT
component  : xorg.library
summary    : libraries which provide client and window-manager helpers for EWMH and
    ICCCM.
description: |
    libraries which provide client and window-manager helpers for EWMH and ICCCM.
builddeps  :
    - pkgconfig(xcb)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
